identifier = "EasyMapping"
name = "Easy Mapping Mod"
author = "oo13 @ github"
version = "1.2.0"
abstract = "A plugin to make you get the local system maps easily."
naev_version = ">= 0.10"
source = { git = "https://github.com/oo13/easy_mapping_plugin_for_naev" }
description = "A plugin to make you get the local system maps easily. You can disable this plugin without any side effects anytime you like."
license = "GPL-3.0-or-later"
release_status = "stable"
tags = [ "casual" ]
# This plugin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This plugin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this plugin.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright Â© 2023-2025 OOTA, Masato
